### ISSUE TITLE
Message Counter Valkyrie Release Checklist

### ISSUE THREAD

**Issue by midhunhk** [midhunhk/message-counter#39]
- [x] String Translations
- [x] Update Version Name and Code in build.gradle
- [x] Update Version details in strings.xml
- [x] Add Change history to VersionHistory.md
- [x] Generate Release Build
- [x] Prepare Release notes and promotional content
- [x] Create Beta Release in Google Play Console
- [x] Upload APK and verify details
- [x] Upload Deobfuscation file
- [x] Publish to Beta
- [x] Merge changes to master
- [x] Complete the Milestone and Tag as release
