### ISSUE TITLE
Message Counter Wyvern Checklist

### ISSUE THREAD

**Issue by midhunhk** [midhunhk/message-counter#51]
- [x] Verify string translations if applicable
- [x] Update Version Name and Code in build.gradle
- [x] Update Version details in strings.xml
- [x] Add Change history to VersionHistory.md 
- [x] Generate Release Build
- [ ] Prepare Release notes and promotional content
- [ ] Create Beta Release in Google Play Console
- [ ] Merge changes to master
- [ ] Upload apk and verify details
- [ ] Upload Deobfuscation file if applicable - [ ] Publish to Beta
- [ ] Complete the Milestone and Tag as release
